version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${NEXTCLOUD_DB_NAME}
      MYSQL_USER: ${NEXTCLOUD_DB_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - frontend
      - nextcloud_backend   # Separate backend network for Nextcloud's database
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: nextcloud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NEXTCLOUD_DB_NAME}
      MYSQL_USER: ${NEXTCLOUD_DB_USER}
      MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - nextcloud_backend   # Only connected to Nextcloud's backend network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - nextcloud_backend   # Isolated within Nextcloud's backend network

networks:
  frontend:
    external: true   # Public-facing network shared with Nginx Proxy Manager
  nextcloud_backend:
    driver: bridge   # Private backend network for Nextcloud's services

volumes:
  nextcloud_data:
  nextcloud_db:
